# Generated by Django 3.2.5 on 2021-07-14 17:33

from django.db import migrations
import django.db.models.deletion
import django.db.models.manager
import salesforce.fields


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', salesforce.fields.SalesforceAutoField(auto_created=True, primary_key=True, serialize=False, sf_managed_model=True, verbose_name='ID')),
                ('name', salesforce.fields.CharField(max_length=80)),
                ('last_modified_date', salesforce.fields.DateTimeField(auto_now=True)),
                ('test_text', salesforce.fields.CharField(db_column='TestText__c', max_length=40, sf_managed=True)),
                ('test_bool', salesforce.fields.BooleanField(db_column='TestBool__c', default=False, sf_managed=True)),
            ],
            options={
                'db_table': 'django_Test__c',
            },
            managers=[
                ('base_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='contact',
            name='cf',
            field=salesforce.fields.DecimalField(blank=True, db_column='Cf__c', decimal_places=0, max_digits=10, null=True, sf_managed=True, unique=True),
        ),
        migrations.CreateModel(
            name='TestDetail',
            fields=[
                ('id', salesforce.fields.SalesforceAutoField(auto_created=True, primary_key=True, serialize=False, sf_managed_model=True, verbose_name='ID')),
                ('contact', salesforce.fields.ForeignKey(blank=True, db_column='Contact__c', null=True, on_delete=django.db.models.deletion.DO_NOTHING, sf_managed=True, to='example.contact')),
                ('parent', salesforce.fields.ForeignKey(db_column='Parent__c', null=True, on_delete=django.db.models.deletion.DO_NOTHING, sf_managed=True, to='example.test')),
            ],
            options={
                'db_table': 'django_Test_detail__c',
                'abstract': False,
                'managed': True,
            },
            managers=[
                ('base_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='test',
            name='contact',
            field=salesforce.fields.ForeignKey(db_column='Contact__c', null=True, on_delete=django.db.models.deletion.DO_NOTHING, sf_managed=True, to='example.contact'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='parent',
            field=salesforce.fields.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='example.test'),
        ),
    ]
