# Generated by Django 3.2.5 on 2021-07-14 22:11

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('example', '0004_auto_rename_table_20210715_0010'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='test',
            options={'verbose_name': 'Test', 'verbose_name_plural': 'Tests'},
        ),
        migrations.AlterModelTable(
            name='test',
            table='django_Test__c',
        ),
    ]
