#!/bin/bash
# expects that "tox" has been run
.tox/py27dj16/bin/coverage run --source salesforce manage.py inspectdb --database=salesforce >/dev/null
for x in py26dj14 py27dj17 py33dj15; do
    .tox/${x}/bin/coverage run -a --source salesforce manage.py test salesforce
done
coverage html
coverage report
