# Generated by Django 2.2.1 on 2019-06-04 05:58

from django.db import migrations
import django.db.models.deletion
import salesforce.fields
import salesforce.models_extend


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', salesforce.models_extend.SfCharAutoField(auto_created=True, db_column='Id', primary_key=True, serialize=False, verbose_name='ID')),
                ('name', salesforce.fields.CharField(max_length=255)),
            ],
            options={
                'db_table': 'Account',
                'abstract': False,
                'base_manager_name': 'objects',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', salesforce.models_extend.SfCharAutoField(auto_created=True, db_column='Id', primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', salesforce.fields.CharField(max_length=80)),
                ('first_name', salesforce.fields.CharField(blank=True, max_length=40)),
                ('account', salesforce.fields.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='test_default_db.Account')),
            ],
            options={
                'db_table': 'Contact',
            },
        ),
    ]
